### ISSUE TITLE
hard-coded lang "words count" in JS

### ISSUE THREAD

**Issue by danmarsden** [SysBind/moodle-atto_wordcount#1]
https://github.com/SysBind/moodle-atto_wordcount/blob/main/yui/src/button/js/button.js#L56

**Comment by AviMoto** [comment]
Hi @danmarsden,
Thanks, I missid that one, I'll fix it ASAP

**Comment by AviMoto** [comment]
Hi @danmarsden,
The hardcoded string was fixed with other fixes.
Thanks again
