### ISSUE TITLE
Text disappears in the setting of questions in a quiz

### ISSUE THREAD

**Issue by numerique-mood** [SysBind/moodle-atto_wordcount#3]
Hi from France,
First of all, Thanks for your plugin, it adds a little bit more to Moodle!
Yesterday, I installed Atto Word Count on my test platform, I saw that in the settings of questions like "drag and drop into text" or "drag and drop onto image", some text disappear or are unreadable (screenshot in attachment). I'm on Moodle 3.10.4 with Moove theme (but it's the same with Boost). When I uninstall your plugin, eveything is OK.
Can you help me please ?
Regards,
Sébastien
![Capture d’écran 2021-07-07 à 08 06 31](https://user-images.githubusercontent.com/84393096/124708253-4ffb6d80-defa-11eb-8d49-f5831d545613.png)

**Comment by AviMoto** [comment]
Hi @numerique-mood
Thanks for reporting this issue, I'll check it and response ASAP
